server:
  servlet:
    context-path: /api
  port: 5000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: username
    password: password
    
    hikari:
      idle-timeout: 10000
  h2:
    console:
      enabled: true

